services:
    - docker

install:
    - docker-compose up -d
    - docker-compose exec node node -v
    - docker-compose exec node npm -v
    - docker-compose exec node npm install
    - docker-compose exec node npm run build

script:
    - docker-compose exec node npm run test
    - docker-compose exec node node .

after_script:
    - docker-compose down
