version: "3"
services:
    node:
        image: "node:10"
        tty: true
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=dev
        volumes:
            - ./:/home/node/app
        command: ""
